CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "calendars" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "description" text,
  "owner_user_id" integer DEFAULT null,
  "is_group" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "calendar_membership" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "calendar_id" int NOT NULL,
  "user_id" int NOT NULL,
  "role" enum(owner,member) NOT NULL
);

CREATE TABLE "events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ics_uid" varchar UNIQUE NOT NULL,
  "title" varchar NOT NULL,
  "description" text,
  "location" varchar,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "timezone" varchar NOT NULL DEFAULT 'UTC',
  "all_day" boolean NOT NULL DEFAULT false,
  "recurrence_rule" text,
  "status" enum(confirmed,tentative,cancelled) NOT NULL DEFAULT 'confirmed',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "proposed_by_user_id" int NOT NULL
);

CREATE TABLE "event_attendance" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "event_id" int NOT NULL,
  "user_id" int NOT NULL,
  "status" enum(accepted,declined,tentative,needs-action) NOT NULL DEFAULT 'needs-action'
);

ALTER TABLE "calendars" ADD FOREIGN KEY ("owner_user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "calendar_membership" ADD FOREIGN KEY ("calendar_id") REFERENCES "calendars" ("id") ON DELETE CASCADE;

ALTER TABLE "calendar_membership" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "events" ADD FOREIGN KEY ("proposed_by_user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

CREATE TABLE "events_calendars" (
  "events_id" integer,
  "calendars_id" integer,
  PRIMARY KEY ("events_id", "calendars_id")
);

ALTER TABLE "events_calendars" ADD FOREIGN KEY ("events_id") REFERENCES "events" ("id");

ALTER TABLE "events_calendars" ADD FOREIGN KEY ("calendars_id") REFERENCES "calendars" ("id");


ALTER TABLE "event_attendance" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE;

ALTER TABLE "event_attendance" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
