-- Generated SQL
CREATE TYPE "membership_role" AS ENUM (
  'owner',
  'member'
);

CREATE TYPE "event_status" AS ENUM (
  'confirmed',
  'tentative',
  'cancelled'
);

CREATE TYPE "attendance_status" AS ENUM (
  'accepted',
  'declined',
  'tentative',
  'needs-action'
);

CREATE TYPE "invitation_status" AS ENUM (
  'accepted',
  'declined',
  'needs-action'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar(50) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "calendars" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" varchar(1000) NOT NULL,
  "owner_user_id" integer,
  "is_group" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "color" varchar(7) NOT NULL
);

CREATE TABLE "memberships" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "calendar_id" int NOT NULL,
  "user_id" int NOT NULL,
  "role" membership_role NOT NULL,
  "color" varchar(7) NOT NULL
);

CREATE TABLE "events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ics_uid" varchar UNIQUE NOT NULL,
  "title" varchar(255) NOT NULL,
  "description" varchar(1000) NOT NULL,
  "location" varchar(255) NOT NULL,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "timezone" varchar(2000) NOT NULL DEFAULT 'UTC',
  "all_day" boolean NOT NULL DEFAULT false,
  "recurrence_rule" text,
  "status" event_status NOT NULL DEFAULT 'confirmed',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "proposed_by_user_id" int NOT NULL
);

CREATE TABLE "events_calendars" (
  "events_id" integer,
  "calendars_id" integer,
  PRIMARY KEY ("events_id", "calendars_id")
);

CREATE TABLE "event_attendance" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "event_id" int NOT NULL,
  "membership_id" int NOT NULL,
  "status" attendance_status NOT NULL DEFAULT 'needs-action'
);

CREATE TABLE "invitations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "calendar_id" int NOT NULL,
  "user_id" int NOT NULL,
  "status" invitation_status NOT NULL DEFAULT 'needs-action',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

ALTER TABLE "calendars" ADD FOREIGN KEY ("owner_user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "memberships" ADD FOREIGN KEY ("calendar_id") REFERENCES "calendars" ("id") ON DELETE CASCADE;

ALTER TABLE "memberships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "events" ADD FOREIGN KEY ("proposed_by_user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "events_calendars" ADD FOREIGN KEY ("events_id") REFERENCES "events" ("id") ON DELETE CASCADE;

ALTER TABLE "events_calendars" ADD FOREIGN KEY ("calendars_id") REFERENCES "calendars" ("id") ON DELETE CASCADE;

ALTER TABLE "event_attendance" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE;

ALTER TABLE "event_attendance" ADD FOREIGN KEY ("membership_id") REFERENCES "memberships" ("id") ON DELETE CASCADE;

ALTER TABLE "invitations" ADD FOREIGN KEY ("calendar_id") REFERENCES "calendars" ("id") ON DELETE CASCADE;

ALTER TABLE "invitations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

-- Manual SQL
ALTER TABLE calendars
ADD CONSTRAINT color_hex_constraint
CHECK (color ~ '^#[A-Fa-f0-9]{6}$');

ALTER TABLE memberships
ADD CONSTRAINT color_hex_constraint
CHECK (color ~ '^#[A-Fa-f0-9]{6}$');